### 新增
POST http://127.0.0.1:13256/subscriber/create
Content-Type: application/json

{
  "title": "设备管理模块",
  "desc": "设备管理模块",
  "subscriberType": "INTERNAL",
  "appName": "",
  "application": "",
  "receiveUrl": ""
}

### 删除
DELETE http://127.0.0.1:13256/subscriber/delete/137454939872952320


### 查询
GET http://127.0.0.1:13256/subscriber/query?subscriberType=INTERNAL
