###
POST http://127.0.0.1:13201/client/publish
Content-Type: application/json

{
  "entity": "test",
  "aggregate": "test1",
  "topic": "example_topic",
  "tag": null,
  "headers": {
    "age": [
      "10"
    ],
    "tenant": [
      "20"
    ]
  },
  "payload": [
    "1",
    "2",
    "3"
  ]
}