###
GET http://localhost:13201/client/testDelay/testAutoAck
###
GET http://localhost:13201/client/testBlock/testAutoAck
###
GET http://localhost:13201/client/testAsync/testAutoAck
###
GET http://localhost:13201/client/testHttp/testAutoAck/10/800
###
GET http://localhost:13202/client/testHttp/testAutoAck/10/800