###
POST http://localhost:8080/bus/receive
Content-Type: application/json

{
  "instanceId" : 1232412345,
  "eventId" : "event_id",
  "bizId" : "biz_id",
  "topic" : "test",
  "headers" : {
    "name" : [ "张三", "李四" ],
    "age" : [ "16" ]
  },
  "payload" : {
    "success" : true,
    "code" : 200,
    "message" : "Success",
    "data" : [ "1", "2", "3" ]
  },
  "timestamp" : 1600421380399
}