spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://127.0.0.1:27017/ideal-bus
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 200ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
