logging:
  config: classpath:logback-spring-dev.xml
server:
  port: 13201
spring:
  application:
    name: IDEAL-BUS-CLIENT
  banner:
    location: banner.txt
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true

ideal:
  bus:
    # 是否开启自动刷新订阅关系
    auto-subscribe: true
    # 应用id
    application-id: 93437173700755456
    # 服务端http基础访问地址
    broker-http-base-url: http://127.0.0.1:13256
    publish:
      # 是否开启事件发布, 默认true
      enabled: true
    consumer:
      # 是否开启消费, 默认false
      enabled: true
      # 核心消费线程数
      core-pool-size: 8
      # 最大消费线程数
      maximum-pool-size: 16
      # 服务端rsocket访问地址
      broker-rsocket-addresses: 127.0.0.1:13266