server:
  port: 13256
eureka:
  client:
    # 是否注册自身到eureka服务器
    register-with-eureka: true
    fetch-registry: true
    # 定时刷新本地缓存时间
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 5
    # 没有心跳的淘汰时间，10秒
    lease-expiration-duration-in-seconds: 10
spring:
  application:
    name: IDEAL-BUS
  banner:
    location: banner.txt
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  rsocket:
    server:
      port: 13266
