logging:
  config: classpath:logback-spring-prd.xml
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://127.0.0.1:27017/ideal-bus?maxPoolSize=4
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 200ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
ideal:
  bus:
    # 当前节点在集群中的编号, 必填且不可重复
    node-id: 1
    # 是否开启存储库定时任务, 每个存储库起一个, 默认false
    enable-storage-scheduling: true
    # 刷新本地缓存的间隔, 默认10分钟
    refresh-local-cache-interval: 10M
    # 消息实例的的过期时间, 默认15天
    route-instance-expire: 1D
    # 事件存储的过期配置, 按需配置, 不在列表中的一直保存
    event-instance-expires:
      - expire: 1D
        topics:
          - broadcast
      - expire: 1D
        topics:
          - testUnAck
          - example_topic
