server:
  port: 13256
spring:
  application:
    name: IDEAL-BUS
  banner:
    location: banner.txt
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  rsocket:
    server:
      port: 13266
